set nocompatible
set nofoldenable
filetype off
set noerrorbells
set number
set showcmd
set noswapfile
set nobackup
set nowritebackup
set encoding=UTF-8
set laststatus=2
set hidden
set ruler
set fileformats=unix,dos,mac
set incsearch
set hlsearch
set ignorecase
set smartcase
set ttyfast
set nocursorcolumn
set nocursorline
set conceallevel=0
set wrap
set textwidth=80
set relativenumber
set autoindent
set smartindent
set complete-=i
set showmatch
set smarttab
set tabstop=2
set shiftwidth=2
set expandtab
set signcolumn=yes
set complete=.,w,b,u,t
set completeopt=longest,menuone
