#!/bin/bash

# random name with lowercase letters
generate_random_name() {
    cat /dev/urandom | tr -dc 'a-z' | head -c 6
}

# check if argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: randomize <extension>"
    exit 1
fi

# iterate over files 
for file in *."$1"; do
    if [ -f "$file" ]; then
        # check if file "was already randomized" before
        base_name=$(basename "$file" ".$1")
        if [ ${#base_name} -eq 6 ]; then
            continue
        fi

        extension="${file##*.}"
        dirname=$(dirname "$file")
        random_name=$(generate_random_name)
        new_name="${random_name}.${extension}"

        # check if file with generated name already exists
        while [ -e "${dirname}/${new_name}" ]; do
            random_name=$(generate_random_name)
            new_name="${random_name}.${extension}"
        done

        echo "$file => $new_name"
        mv "$file" "${dirname}/${new_name}"
    fi
done
