local config = "plugins.config."

require(config .. "actions")
require(config .. "bufferline")
require(config .. "comment")
require(config .. "formatter")
require(config .. "general")
require(config .. "ibl")
require(config .. "lspcmp")
require(config .. "lualine")
require(config .. "mason")
require(config .. "mkdnflow")
require(config .. "nvimtree")
require(config .. "scissors")
require(config .. "telescope")
require(config .. "toggleterm")
require(config .. "treesitter")
require(config .. "trouble")
