local config = "plugins.config."

require(config .. "actions")
require(config .. "bufferline")
require(config .. "cmp")
require(config .. "colorizer")
require(config .. "comment")
require(config .. "formatter")
require(config .. "ibl")
require(config .. "lsp")
require(config .. "lualine")
require(config .. "luasnip")
require(config .. "mason")
require(config .. "mini")
require(config .. "mkdnflow")
require(config .. "nvimtree")
require(config .. "scissors")
require(config .. "telescope")
require(config .. "toggleterm")
require(config .. "trouble")
